name: On push to master, build and deploy changes to ECR

on:
  push:
    branches:
      - master

jobs:
  build_npm_dependencies:
    runs-on: ubuntu-latest
    name: npm build
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: '0'
          
      - name: npm/yarn/pnpm install
      # You may pin to the exact commit or the version.
      # uses: Jaid/action-npm-install@9483da054882538350947c4147de4c8adbf0d597
        uses: Jaid/action-npm-install@v1.2.4
        with:
          # NODE_ENV setting for installing execution (affects the amount of dependencies installed, but I would recommend keeping development in any case).
          nodeEnv: 'development' # optional, default is development
          # Can be "npm", "yarn", "pnpm" or "auto". "auto" will determine the package manager by looking into the repo's files. This is very accurate, so you normally don't want to change this.
          packageManager: 'auto' # optional, default is auto
          # If true and node_modules folder already exists, this action will be skipped assuming npm install is not required.
          skipIfNodeModulesExists: 'false' # optional, default is false

      - name: Bump version and push tag
        id: tagging
        if: contains(github.ref, 'master')
        uses: anothrNick/github-tag-action@1.21.0
        env:
          DEFAULT_BUMP: patch
          INITIAL_VERSION: 1.5.0
          RELEASE_BRANCHES: master
          
      - name: Build Docker image and Push to ECR
        uses: kciter/aws-ecr-action@v1
        env:
          repo: cloud-reports
          INSTANCE_ROLE_ARNS: arn:aws:iam::838837044885:role/devops
          IMG: cloud-reports
          IAMROLEARN: arn:aws:iam::838837044885:role/devops
        with:
          access_key_id: ${{ secrets.CIUSER_AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.CIUSER_AWS_SECRET_ACCESS_KEY }}
          account_id: 838837044885
          dockerfile: ./Dockerfile
          path: ./
          # extra_build_args:
          repo: ${{ env.repo }}
          region: eu-central-1
          tags: 1.6.0
          create_repo: false
